language: python

python:
- 3.6
- 3.5
- 2.7

env:
  global:
    - secure: nvNZKwMD2xgZhG3Qo5310bbBhsIhSsewFbczSZSFr5utEcfGYAGur6dfEIAeECKtcUk20eRX/KXTedxdv7zIx+39jnOjmLkYes9Qi/paHXGnxH0DI0PHDdAzwKtqhh+rnrFOk/OK/y5ypyF5z5KvrrItLx2aKmBIw19lHPks3CmxW659QQ1uX0dFQihUALKNaB5SqYfAxQ9aV7FVaBWlLig21uPx2cZoJ9ikS6RxP27peUJPZgePeU2dnYVLKgsaTL8NwuzNKNOJCtdSlAxanLbeMwvyxHxUnVGT1t2LzEHfG6EJANVKh8IDl0wMlLunjpeLpbIgKlyPM2kGqhoKGSoqh8uxSmggfJlLWwiBAdFJOkfC2Avt63q8K17LD7LvoIiAMHznzzvgVEPSx8nW7jlzmfCKnGeytiYHSbBoDe4YxusWhoETof2+4gxum22tzrt/IEgFawHa5BcBdw9tKuGKtMJpTnwXlxJlGU1sDOJdgpeSGxADw3Us+v460KzrSd1MGEOwhD7cbl9GHdI/LaVJfcGOp9kPICXPcXQIk+hvu0nJCkmMQ1Uojhhn+rygBSGsHUDAU7/CV6DRrghh+frYv4QHhjrwseNsmst27J+EPP3bBW0tF2ousv8/GWKFN/g7mEq/UHeSekgSU73Ni0nGJHpG8sPExcqe3jMMUXU=

install: pip install -U tox-travis

script: tox

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: assemblyai
  password:
    secure: pxqd/h6a7/pUQ3fTQ4LYhnMTO1f10RE+EiWiiW71cWj32DHe0v+ZAO87YfmuWD26QXq7yde7xihdr3w6mXzVC73vV/0Rpnu0eBS9rhWK0EQ78syfLDSofY+HjOK6GhmCJh9kc12oknM1umSazPfOuFsY5+2AShgaKG/3vFFsaAyi/cZ7htdy0QoFV0a8e0fWMlOX7d9DQVIouJ4xqWpwS0Ivv9kJxJeFQFiGEGT4uCf+wQwh7ZtIYJujczs2SQQC90b2Hfj7ET71AsCc5TntHgEySZPQC2zuhWu4h51Zi6n9+NqwvXI4eMj+Lan28MRfaz2pxJ5lK9327gKa42Ba1B7BisUKDLvd9zD/7ODhZbmc8XZymZKZceQMgM+cK7TU3cZYDMY4hgLBaztPWaG98Np94mSjdShVHAUw/n0SYEvZ1R7ND7pSmJYEuxzuAAjVBMLlI8uO3CvVvsoyuExqINNxAfIe/AEct0/QUA6x30huumk6G82zXJsVeSZZH3VpO91Dp4C7NqxwKnHge6SYcaey/wU1U0cvTag2zlU9oNUBAXR5Ff/vWOHS29RSnNiE2JK22bCfgztAfs4ZqPscfa235xyAF7uOlp4x75k8LTaBJzLJZR6LaBkrRscuM2/2+0uk8YCm7bXBAJ9zBFQ71TmJkfDkiwWgtpWdO/wc/4c=
  on:
    tags: true
    repo: AssemblyAI/assemblyai-python-sdk
    python: 3.6

after_success:
  - bash < (curl -s https://codecov.io/bash)
